dependencies {
    implementation(libs.balmFabric) {
        changing = libs.versions.balm.get().contains("SNAPSHOT")
    }

    compileOnly("org.projectlombok:lombok:1.18.46")
    annotationProcessor("org.projectlombok:lombok:1.18.46")

    testCompileOnly("org.projectlombok:lombok:1.18.46")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.46")

    // compile against the JEI API but do not include it at runtime
    compileOnly("mezz.jei:jei-${libs.versions.minecraft.get()}-fabric-api:${libs.versions.jei.get()}")
    // at runtime, use the full JEI jar for Fabric
    //runtimeOnly("mezz.jei:jei-${libs.versions.minecraft.get()}-fabric:${libs.versions.jei.get()}")

    implementation("maven.modrinth:jade:${libs.versions.jade.get()}+fabric")
}