dependencies {
    implementation(libs.balmCommon) {
        changing = libs.versions.balm.get().endsWith("SNAPSHOT")
    }
    accessTransformers(libs.balmCommon)

    compileOnly("org.projectlombok:lombok:1.18.46")
    annotationProcessor("org.projectlombok:lombok:1.18.46")

    testCompileOnly("org.projectlombok:lombok:1.18.46")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.46")

    // compile against the JEI API but do not include it at runtime
    compileOnly("mezz.jei:jei-${libs.versions.minecraft.get()}-common-api:${libs.versions.jei.get()}")
}
